from pytest_pyodide import run_in_pyodide


@run_in_pyodide
def test_ssl_import(selenium):
    import sys

    # See src/py/{ssl.py, _ssl.py} for details.

    # Test all public attributes of the ssl module can be accessed
    # https://docs.python.org/3.13/library/ssl.html

    # If you are not sure, you can generate this list by running:
    """
import ssl
public_attrs = [attr for attr in dir(ssl) if not attr.startswith('_')]
print("from ssl import (\n{})".format(",\n    ".join(public_attrs)))
    """

    # Guardrail to ensure we don't forget to update this test when Python version changes
    assert sys.version_info.minor == 13

    from ssl import (  # type: ignore[attr-defined]  # noqa: F401
        ALERT_DESCRIPTION_ACCESS_DENIED,
        ALERT_DESCRIPTION_BAD_CERTIFICATE,
        ALERT_DESCRIPTION_BAD_CERTIFICATE_HASH_VALUE,
        ALERT_DESCRIPTION_BAD_CERTIFICATE_STATUS_RESPONSE,
        ALERT_DESCRIPTION_BAD_RECORD_MAC,
        ALERT_DESCRIPTION_CERTIFICATE_EXPIRED,
        ALERT_DESCRIPTION_CERTIFICATE_REVOKED,
        ALERT_DESCRIPTION_CERTIFICATE_UNKNOWN,
        ALERT_DESCRIPTION_CERTIFICATE_UNOBTAINABLE,
        ALERT_DESCRIPTION_CLOSE_NOTIFY,
        ALERT_DESCRIPTION_DECODE_ERROR,
        ALERT_DESCRIPTION_DECOMPRESSION_FAILURE,
        ALERT_DESCRIPTION_DECRYPT_ERROR,
        ALERT_DESCRIPTION_HANDSHAKE_FAILURE,
        ALERT_DESCRIPTION_ILLEGAL_PARAMETER,
        ALERT_DESCRIPTION_INSUFFICIENT_SECURITY,
        ALERT_DESCRIPTION_INTERNAL_ERROR,
        ALERT_DESCRIPTION_NO_RENEGOTIATION,
        ALERT_DESCRIPTION_PROTOCOL_VERSION,
        ALERT_DESCRIPTION_RECORD_OVERFLOW,
        ALERT_DESCRIPTION_UNEXPECTED_MESSAGE,
        ALERT_DESCRIPTION_UNKNOWN_CA,
        ALERT_DESCRIPTION_UNKNOWN_PSK_IDENTITY,
        ALERT_DESCRIPTION_UNRECOGNIZED_NAME,
        ALERT_DESCRIPTION_UNSUPPORTED_CERTIFICATE,
        ALERT_DESCRIPTION_UNSUPPORTED_EXTENSION,
        ALERT_DESCRIPTION_USER_CANCELLED,
        CERT_NONE,
        CERT_OPTIONAL,
        CERT_REQUIRED,
        CHANNEL_BINDING_TYPES,
        HAS_ALPN,
        HAS_ECDH,
        HAS_NEVER_CHECK_COMMON_NAME,
        HAS_NPN,
        HAS_PHA,
        HAS_PSK,
        HAS_SNI,
        OP_ALL,
        OP_CIPHER_SERVER_PREFERENCE,
        OP_ENABLE_KTLS,
        OP_ENABLE_MIDDLEBOX_COMPAT,
        OP_IGNORE_UNEXPECTED_EOF,
        OP_LEGACY_SERVER_CONNECT,
        OP_NO_COMPRESSION,
        OP_NO_RENEGOTIATION,
        OP_NO_TICKET,
        OP_SINGLE_DH_USE,
        OP_SINGLE_ECDH_USE,
        OPENSSL_VERSION,
        OPENSSL_VERSION_INFO,
        OPENSSL_VERSION_NUMBER,
        PEM_FOOTER,
        PEM_HEADER,
        PROTOCOL_TLS,
        PROTOCOL_TLS_CLIENT,
        PROTOCOL_TLS_SERVER,
        SSL_ERROR_EOF,
        SSL_ERROR_INVALID_ERROR_CODE,
        SSL_ERROR_SSL,
        SSL_ERROR_SYSCALL,
        SSL_ERROR_WANT_CONNECT,
        SSL_ERROR_WANT_READ,
        SSL_ERROR_WANT_WRITE,
        SSL_ERROR_WANT_X509_LOOKUP,
        SSL_ERROR_ZERO_RETURN,
        VERIFY_ALLOW_PROXY_CERTS,
        VERIFY_CRL_CHECK_CHAIN,
        VERIFY_CRL_CHECK_LEAF,
        VERIFY_DEFAULT,
        VERIFY_X509_PARTIAL_CHAIN,
        VERIFY_X509_STRICT,
        VERIFY_X509_TRUSTED_FIRST,
        AlertDescription,
        CertificateError,
        DefaultVerifyPaths,
        DER_cert_to_PEM_cert,
        HAS_SSLv2,
        HAS_SSLv3,
        HAS_TLSv1,
        HAS_TLSv1_1,
        HAS_TLSv1_2,
        HAS_TLSv1_3,
        MemoryBIO,
        OP_NO_SSLv2,
        OP_NO_SSLv3,
        OP_NO_TLSv1,
        OP_NO_TLSv1_1,
        OP_NO_TLSv1_2,
        OP_NO_TLSv1_3,
        Options,
        PEM_cert_to_DER_cert,
        PROTOCOL_SSLv23,
        PROTOCOL_TLSv1,
        PROTOCOL_TLSv1_1,
        PROTOCOL_TLSv1_2,
        Purpose,
        RAND_add,
        RAND_bytes,
        RAND_status,
        # coming from socket module
        # SOCK_STREAM,
        # SOL_SOCKET,
        # SO_TYPE,
        SSLCertVerificationError,
        SSLContext,
        SSLEOFError,
        SSLError,
        SSLErrorNumber,
        SSLObject,
        SSLSession,
        SSLSocket,
        SSLSyscallError,
        SSLWantReadError,
        SSLWantWriteError,
        SSLZeroReturnError,
        TLSVersion,
        VerifyFlags,
        VerifyMode,
        cert_time_to_seconds,
        create_connection,
        create_default_context,
        # errno module
        # errno,
        get_default_verify_paths,
        get_protocol_name,
        get_server_certificate,
        socket_error,
    )

    create_default_context()  # just a sanity check
