#!/bin/sh
DOCKER_PORT=8000
SYSTEM_PORT=8000

docker run -p $SYSTEM_PORT:$DOCKER_PORT --rm -v $PWD:/src --user root -e NB_UID=$UID -e NB_GID=$GID -it iodide/pyodide-env:0.3.1 /bin/bash

#Just in case you do not know what all of these commadnds do,
#Here is the dockermentation. 

#Run a Docker command. 
    #docker run

#This maps the docker port to your server's
#publicly visible prots. 
    #-p $SYSTEM_PORT:$DOCKER_PORT

#This removes the docker container after it is done processing.
#Since we use the volume command, the results will persist in the
#currnet-directory/src
    #--rm

#This maps the  /src directory in the container to the
#current-directory/src in your computer.
#Thus the results are saved in the current-directory/src.
   #-v $PWD:/src

#This says to treat the user as root.
#If you are publishing this container on a publically visible port
#then this may be a security hole. 
   #--user root


#Set two environment variables.
#Specifically the current user's uid and
#the current users groupid.
#thus the new current-directory/src will have correct permissions. 
   #-e NB_UID=$UID
   #-e NB_GID=$GID


#Tells the Docker container to stay connected to the terminal
#and take its input from and send the output to the terminal. 
   #-it

#This is the name of the Docker container to invoke
#Along witht the tag fo the current versi0n. 
    #iodide/pyodide-env:0.3.1

#And inside of the container invoke the bash command. 
    #/bin/bash

#And then once the contain is invoked tell it to make the softwre
    #$ make

