#!/bin/bash
set -ex
export PYODIDE_ROOT
PYODIDE_ROOT=$(pwd)
echo "$PYODIDE_ROOT"
make pyodide_build
rm -rf test-cmdline-runner
mkdir test-cmdline-runner
cd test-cmdline-runner || exit

python -m venv .venv-host
# shellcheck source=/dev/null
source .venv-host/bin/activate

chmod +x "$(pyodide config get interpreter)"
pyodide venv .venv-pyodide
# shellcheck source=/dev/null
source .venv-pyodide/bin/activate

git clone https://github.com/python-attrs/attrs --depth 1 --branch 25.3.0
cd attrs || exit
pip install ".[tests]"
# mypy_plugins uses pty and stuff that isn't supported on Emscripten.
../.venv-pyodide/bin/pip uninstall pytest-mypy-plugins -y
# Deselect tests that fail on Python 3.15.
# TODO: remove skips when attrs releases a version compatible with Python 3.15
python -m pytest -k 'not mypy' \
    --deselect 'tests/test_make.py::TestClassBuilder::test_no_references_to_original_when_using_cached_property' \
    --deselect 'tests/test_validators.py::TestMatchesRe::test_catches_invalid_func'
