#!/bin/sh
DIRECTORY=$(dirname "$(realpath "$0")")
export PYODIDE_PATH="../dist"

set -e

ARGS=$(node -e "$(cat <<EOF
let major_version = Number(process.version.split(".")[0].slice(1));
if(major_version < 14) {
    console.error("Need node version >= 14. Got node version", process.version);
    process.exit(1);
}
if(major_version == 14){
    process.stdout.write(" --experimental-wasm-bigint ");
}
EOF
)")

FULL_ARGS="$ARGS" "$DIRECTORY"/python.js "$@"

exec node "$FULL_ARGS"
