name: Deploy to GitHub Pages

on:
  push:
    # The update_cross_build_releases.yml workflow updates the cross-build environments metadata
    # file and pushes it to the main branch. This workflow gets triggered by that push.
    branches:
      - main
    paths:
      # This workflow only runs if this specific file changes
      - pyodide-cross-build-environments.json
  workflow_dispatch:
  schedule:
    # Run every day at 03:00 UTC
    - cron: "0 3 * * *"

permissions: {}

jobs:
  deploy:
    name: Deploy pyodide-cross-build-environments.json to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}/api/pyodide-cross-build-environments.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Prepare artifact
        run: |
          mkdir -p ./_site/api
          cp pyodide-cross-build-environments.json ./_site/api/pyodide-cross-build-environments.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
