name: Deploy to GitHub Pages

on:
  push:
    # The update_cross_build_releases.yml workflow updates the cross-build environments metadata
    # file and pushes it to the main branch. This workflow gets triggered by that push.
    branches:
      - main
    paths:
      # This workflow only runs if these specific files change
      - pyodide-cross-build-environments-v2.json
      - pyodide-cross-build-environments-v1.json
  workflow_dispatch:
  schedule:
    # Run every day at 03:00 UTC
    - cron: "0 3 * * *"

permissions: {}

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy cross-build environments metadata to GitHub Pages
    permissions:
      contents: read
      pages: write # for deploying to GitHub Pages
      id-token: write # for OIDC trusted publishing to GitHub Pages
    environment:
      name: github-pages
      # This is cosmetically used in the deployment logs as the clickable link; it won't affect
      # our existing deployments since the pages are published based on what we have below in _site
      url: ${{ steps.deployment.outputs.page_url }}/api/v2/pyodide-cross-build-environments.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

        # v2: same as v1, but with published_at field to include ISO 8601 timestamp of the release publication (canonical URL for pyodide-build >= 0.34.5)
        # v1: original starting URL for pyodide-build < 0.34.5, which didn't have published_at.
        # We will continue to maintain both for backward compatibility with earlier pyodide-build versions
      - name: Prepare artifacts
        run: |
          mkdir -p ./_site/api/v2
          cp pyodide-cross-build-environments-v2.json ./_site/api/v2/pyodide-cross-build-environments.json
          cp pyodide-cross-build-environments-v1.json ./_site/api/pyodide-cross-build-environments.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
