name: Update cross-build metadata file

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version number to update to. This should not contain the 'v' prefix, since our releases on GitHub do not have it."
        required: true

env:
  version: ${{ github.event_name == 'release' && github.event.release.tag_name || github.event.inputs.version }}

permissions: {}

jobs:
  update_cross_build_releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      # Note: we check out the main branch so that the cross-build metadata
      # file is always updated on top of the latest state of the repository.
      - name: Checkout main branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          ref: main
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.14

      - name: Install pyodide-build
        run: |
          python -m pip install --upgrade pip
          make pyodide_build

      - name: Update cross-build metadata file
        id: update_cross_build_metadata
        working-directory: tools
        env:
          VERSION: ${{ env.version }}
        run: |
          python update_cross_build_releases.py "$VERSION"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update cross-build metadata file for version ${{ env.version }} [skip ci]
          title: Update cross-build metadata file for version ${{ env.version }}
          body: |
            This PR updates the cross-build metadata file for the new version ${{ env.version }}.
            Requesting a review from the @pyodide/core team.
          branch: update-cross-build-metadata-${{ env.version }}
          base: main
          branch-suffix: timestamp

      - name: Create an issue if the update fails
        if: failure() || steps.update_cross_build_metadata.outcome == 'failure'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.version }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          ASSIGNEE: ${{ github.actor }}
        run: |
          gh issue create \
            --title "Update cross-build metadata file for version ${VERSION} failed" \
            --assignee "${ASSIGNEE}" \
            --body "## Description

          The update of the cross-build metadata file for version ${VERSION} failed.

          ## Additional information

          Please check the logs at ${RUN_URL}
          for more information and update the metadata file manually if necessary."
